// Auto-generated from ucum-essence.xml — DO NOT EDIT
// Source: https://unitsofmeasure.org

export interface PrefixDef {
  code: string;
  name: string;
  value: string; // decimal string like '1e3', '1e-6'
}

export interface BaseUnitDef {
  code: string;
  name: string;
  property: string;
  dim: string; // single char dimension
}

export interface UnitDef {
  code: string;
  name: string;
  property: string;
  isMetric: boolean;
  isSpecial: boolean;
  isArbitrary: boolean;
  class: string;
  value?: { unit: string; value: string }; // UCUM expression + multiplier
}

export const UCUM_VERSION = '2.2';

export const PREFIXES: readonly PrefixDef[] = [
  { code: 'Y', name: 'yotta', value: '1e24' },
  { code: 'Z', name: 'zetta', value: '1e21' },
  { code: 'E', name: 'exa', value: '1e18' },
  { code: 'P', name: 'peta', value: '1e15' },
  { code: 'T', name: 'tera', value: '1e12' },
  { code: 'G', name: 'giga', value: '1e9' },
  { code: 'M', name: 'mega', value: '1e6' },
  { code: 'k', name: 'kilo', value: '1e3' },
  { code: 'h', name: 'hecto', value: '1e2' },
  { code: 'da', name: 'deka', value: '1e1' },
  { code: 'd', name: 'deci', value: '1e-1' },
  { code: 'c', name: 'centi', value: '1e-2' },
  { code: 'm', name: 'milli', value: '1e-3' },
  { code: 'u', name: 'micro', value: '1e-6' },
  { code: 'n', name: 'nano', value: '1e-9' },
  { code: 'p', name: 'pico', value: '1e-12' },
  { code: 'f', name: 'femto', value: '1e-15' },
  { code: 'a', name: 'atto', value: '1e-18' },
  { code: 'z', name: 'zepto', value: '1e-21' },
  { code: 'y', name: 'yocto', value: '1e-24' },
  { code: 'Ki', name: 'kibi', value: '1024' },
  { code: 'Mi', name: 'mebi', value: '1048576' },
  { code: 'Gi', name: 'gibi', value: '1073741824' },
  { code: 'Ti', name: 'tebi', value: '1099511627776' },
] as const;

export const BASE_UNITS: readonly BaseUnitDef[] = [
  { code: 'm', name: 'meter', property: 'length', dim: 'L' },
  { code: 's', name: 'second', property: 'time', dim: 'T' },
  { code: 'g', name: 'gram', property: 'mass', dim: 'M' },
  { code: 'rad', name: 'radian', property: 'plane angle', dim: 'A' },
  { code: 'K', name: 'kelvin', property: 'temperature', dim: 'C' },
  { code: 'C', name: 'coulomb', property: 'electric charge', dim: 'Q' },
  { code: 'cd', name: 'candela', property: 'luminous intensity', dim: 'F' },
] as const;

export const DEFINED_UNITS: readonly UnitDef[] = [
  { code: '10*', name: 'the number ten for arbitrary powers', property: 'number', isMetric: false, isSpecial: false, isArbitrary: false, class: 'dimless', value: { unit: '1', value: '10' } },
  { code: '10^', name: 'the number ten for arbitrary powers', property: 'number', isMetric: false, isSpecial: false, isArbitrary: false, class: 'dimless', value: { unit: '1', value: '10' } },
  { code: '[pi]', name: 'the number pi', property: 'number', isMetric: false, isSpecial: false, isArbitrary: false, class: 'dimless', value: { unit: '1', value: '3.1415926535897932384626433832795028841971693993751058209749445923' } },
  { code: '%', name: 'percent', property: 'fraction', isMetric: false, isSpecial: false, isArbitrary: false, class: 'dimless', value: { unit: '10*-2', value: '1' } },
  { code: '[ppth]', name: 'parts per thousand', property: 'fraction', isMetric: false, isSpecial: false, isArbitrary: false, class: 'dimless', value: { unit: '10*-3', value: '1' } },
  { code: '[ppm]', name: 'parts per million', property: 'fraction', isMetric: false, isSpecial: false, isArbitrary: false, class: 'dimless', value: { unit: '10*-6', value: '1' } },
  { code: '[ppb]', name: 'parts per billion', property: 'fraction', isMetric: false, isSpecial: false, isArbitrary: false, class: 'dimless', value: { unit: '10*-9', value: '1' } },
  { code: '[pptr]', name: 'parts per trillion', property: 'fraction', isMetric: false, isSpecial: false, isArbitrary: false, class: 'dimless', value: { unit: '10*-12', value: '1' } },
  { code: 'mol', name: 'mole', property: 'amount of substance', isMetric: true, isSpecial: false, isArbitrary: false, class: 'si', value: { unit: '10*23', value: '6.02214076' } },
  { code: 'sr', name: 'steradian', property: 'solid angle', isMetric: true, isSpecial: false, isArbitrary: false, class: 'si', value: { unit: 'rad2', value: '1' } },
  { code: 'Hz', name: 'hertz', property: 'frequency', isMetric: true, isSpecial: false, isArbitrary: false, class: 'si', value: { unit: 's-1', value: '1' } },
  { code: 'N', name: 'newton', property: 'force', isMetric: true, isSpecial: false, isArbitrary: false, class: 'si', value: { unit: 'kg.m/s2', value: '1' } },
  { code: 'Pa', name: 'pascal', property: 'pressure', isMetric: true, isSpecial: false, isArbitrary: false, class: 'si', value: { unit: 'N/m2', value: '1' } },
  { code: 'J', name: 'joule', property: 'energy', isMetric: true, isSpecial: false, isArbitrary: false, class: 'si', value: { unit: 'N.m', value: '1' } },
  { code: 'W', name: 'watt', property: 'power', isMetric: true, isSpecial: false, isArbitrary: false, class: 'si', value: { unit: 'J/s', value: '1' } },
  { code: 'A', name: 'ampère', property: 'electric current', isMetric: true, isSpecial: false, isArbitrary: false, class: 'si', value: { unit: 'C/s', value: '1' } },
  { code: 'V', name: 'volt', property: 'electric potential', isMetric: true, isSpecial: false, isArbitrary: false, class: 'si', value: { unit: 'J/C', value: '1' } },
  { code: 'F', name: 'farad', property: 'electric capacitance', isMetric: true, isSpecial: false, isArbitrary: false, class: 'si', value: { unit: 'C/V', value: '1' } },
  { code: 'Ohm', name: 'ohm', property: 'electric resistance', isMetric: true, isSpecial: false, isArbitrary: false, class: 'si', value: { unit: 'V/A', value: '1' } },
  { code: 'S', name: 'siemens', property: 'electric conductance', isMetric: true, isSpecial: false, isArbitrary: false, class: 'si', value: { unit: 'Ohm-1', value: '1' } },
  { code: 'Wb', name: 'weber', property: 'magnetic flux', isMetric: true, isSpecial: false, isArbitrary: false, class: 'si', value: { unit: 'V.s', value: '1' } },
  { code: 'Cel', name: 'degree Celsius', property: 'temperature', isMetric: true, isSpecial: true, isArbitrary: false, class: 'si', value: { unit: 'cel(1 K)', value: '' } },
  { code: 'T', name: 'tesla', property: 'magnetic flux density', isMetric: true, isSpecial: false, isArbitrary: false, class: 'si', value: { unit: 'Wb/m2', value: '1' } },
  { code: 'H', name: 'henry', property: 'inductance', isMetric: true, isSpecial: false, isArbitrary: false, class: 'si', value: { unit: 'Wb/A', value: '1' } },
  { code: 'lm', name: 'lumen', property: 'luminous flux', isMetric: true, isSpecial: false, isArbitrary: false, class: 'si', value: { unit: 'cd.sr', value: '1' } },
  { code: 'lx', name: 'lux', property: 'illuminance', isMetric: true, isSpecial: false, isArbitrary: false, class: 'si', value: { unit: 'lm/m2', value: '1' } },
  { code: 'Bq', name: 'becquerel', property: 'radioactivity', isMetric: true, isSpecial: false, isArbitrary: false, class: 'si', value: { unit: 's-1', value: '1' } },
  { code: 'Gy', name: 'gray', property: 'energy dose', isMetric: true, isSpecial: false, isArbitrary: false, class: 'si', value: { unit: 'J/kg', value: '1' } },
  { code: 'Sv', name: 'sievert', property: 'dose equivalent', isMetric: true, isSpecial: false, isArbitrary: false, class: 'si', value: { unit: 'J/kg', value: '1' } },
  { code: 'gon', name: 'gon', property: 'plane angle', isMetric: false, isSpecial: false, isArbitrary: false, class: 'iso1000', value: { unit: 'deg', value: '0.9' } },
  { code: 'deg', name: 'degree', property: 'plane angle', isMetric: false, isSpecial: false, isArbitrary: false, class: 'iso1000', value: { unit: '[pi].rad/360', value: '2' } },
  { code: '\'', name: 'minute', property: 'plane angle', isMetric: false, isSpecial: false, isArbitrary: false, class: 'iso1000', value: { unit: 'deg/60', value: '1' } },
  { code: '\'\'', name: 'second', property: 'plane angle', isMetric: false, isSpecial: false, isArbitrary: false, class: 'iso1000', value: { unit: '\'/60', value: '1' } },
  { code: 'l', name: 'liter', property: 'volume', isMetric: true, isSpecial: false, isArbitrary: false, class: 'iso1000', value: { unit: 'dm3', value: '1' } },
  { code: 'L', name: 'liter', property: 'volume', isMetric: true, isSpecial: false, isArbitrary: false, class: 'iso1000', value: { unit: 'l', value: '1' } },
  { code: 'ar', name: 'are', property: 'area', isMetric: true, isSpecial: false, isArbitrary: false, class: 'iso1000', value: { unit: 'm2', value: '100' } },
  { code: 'min', name: 'minute', property: 'time', isMetric: false, isSpecial: false, isArbitrary: false, class: 'iso1000', value: { unit: 's', value: '60' } },
  { code: 'h', name: 'hour', property: 'time', isMetric: false, isSpecial: false, isArbitrary: false, class: 'iso1000', value: { unit: 'min', value: '60' } },
  { code: 'd', name: 'day', property: 'time', isMetric: false, isSpecial: false, isArbitrary: false, class: 'iso1000', value: { unit: 'h', value: '24' } },
  { code: 'a_t', name: 'tropical year', property: 'time', isMetric: false, isSpecial: false, isArbitrary: false, class: 'iso1000', value: { unit: 'd', value: '365.24219' } },
  { code: 'a_j', name: 'mean Julian year', property: 'time', isMetric: false, isSpecial: false, isArbitrary: false, class: 'iso1000', value: { unit: 'd', value: '365.25' } },
  { code: 'a_g', name: 'mean Gregorian year', property: 'time', isMetric: false, isSpecial: false, isArbitrary: false, class: 'iso1000', value: { unit: 'd', value: '365.2425' } },
  { code: 'a', name: 'year', property: 'time', isMetric: false, isSpecial: false, isArbitrary: false, class: 'iso1000', value: { unit: 'a_j', value: '1' } },
  { code: 'wk', name: 'week', property: 'time', isMetric: false, isSpecial: false, isArbitrary: false, class: 'iso1000', value: { unit: 'd', value: '7' } },
  { code: 'mo_s', name: 'synodal month', property: 'time', isMetric: false, isSpecial: false, isArbitrary: false, class: 'iso1000', value: { unit: 'd', value: '29.53059' } },
  { code: 'mo_j', name: 'mean Julian month', property: 'time', isMetric: false, isSpecial: false, isArbitrary: false, class: 'iso1000', value: { unit: 'a_j/12', value: '1' } },
  { code: 'mo_g', name: 'mean Gregorian month', property: 'time', isMetric: false, isSpecial: false, isArbitrary: false, class: 'iso1000', value: { unit: 'a_g/12', value: '1' } },
  { code: 'mo', name: 'month', property: 'time', isMetric: false, isSpecial: false, isArbitrary: false, class: 'iso1000', value: { unit: 'mo_j', value: '1' } },
  { code: 't', name: 'tonne', property: 'mass', isMetric: true, isSpecial: false, isArbitrary: false, class: 'iso1000', value: { unit: 'kg', value: '1e3' } },
  { code: 'bar', name: 'bar', property: 'pressure', isMetric: true, isSpecial: false, isArbitrary: false, class: 'iso1000', value: { unit: 'Pa', value: '1e5' } },
  { code: 'u', name: 'unified atomic mass unit', property: 'mass', isMetric: true, isSpecial: false, isArbitrary: false, class: 'iso1000', value: { unit: 'g', value: '1.66053906660e-24' } },
  { code: 'eV', name: 'electronvolt', property: 'energy', isMetric: true, isSpecial: false, isArbitrary: false, class: 'iso1000', value: { unit: '[e].V', value: '1' } },
  { code: 'AU', name: 'astronomic unit', property: 'length', isMetric: false, isSpecial: false, isArbitrary: false, class: 'iso1000', value: { unit: 'Mm', value: '149597.870691' } },
  { code: 'pc', name: 'parsec', property: 'length', isMetric: true, isSpecial: false, isArbitrary: false, class: 'iso1000', value: { unit: 'm', value: '3.085678e16' } },
  { code: '[c]', name: 'velocity of light', property: 'velocity', isMetric: true, isSpecial: false, isArbitrary: false, class: 'const', value: { unit: 'm/s', value: '299792458' } },
  { code: '[h]', name: 'Planck constant', property: 'action', isMetric: true, isSpecial: false, isArbitrary: false, class: 'const', value: { unit: 'J.s', value: '6.62607015e-34' } },
  { code: '[k]', name: 'Boltzmann constant', property: '(unclassified)', isMetric: true, isSpecial: false, isArbitrary: false, class: 'const', value: { unit: 'J/K', value: '1.380649e-23' } },
  { code: '[eps_0]', name: 'permittivity of vacuum', property: 'electric permittivity', isMetric: true, isSpecial: false, isArbitrary: false, class: 'const', value: { unit: 'F/m', value: '8.854187817e-12' } },
  { code: '[mu_0]', name: 'permeability of vacuum', property: 'magnetic permeability', isMetric: true, isSpecial: false, isArbitrary: false, class: 'const', value: { unit: '4.[pi].10*-7.N/A2', value: '1' } },
  { code: '[e]', name: 'elementary charge', property: 'electric charge', isMetric: true, isSpecial: false, isArbitrary: false, class: 'const', value: { unit: 'C', value: '1.602176634e-19' } },
  { code: '[m_e]', name: 'electron mass', property: 'mass', isMetric: true, isSpecial: false, isArbitrary: false, class: 'const', value: { unit: 'kg', value: '9.1093837139e-31' } },
  { code: '[m_p]', name: 'proton mass', property: 'mass', isMetric: true, isSpecial: false, isArbitrary: false, class: 'const', value: { unit: 'kg', value: '1.67262192595e-27' } },
  { code: '[G]', name: 'Newtonian constant of gravitation', property: '(unclassified)', isMetric: true, isSpecial: false, isArbitrary: false, class: 'const', value: { unit: 'm3.kg-1.s-2', value: '6.67430e-11' } },
  { code: '[g]', name: 'standard acceleration of free fall', property: 'acceleration', isMetric: true, isSpecial: false, isArbitrary: false, class: 'const', value: { unit: 'm/s2', value: '980665e-5' } },
  { code: 'atm', name: 'standard atmosphere', property: 'pressure', isMetric: false, isSpecial: false, isArbitrary: false, class: 'const', value: { unit: 'Pa', value: '101325' } },
  { code: '[ly]', name: 'light-year', property: 'length', isMetric: true, isSpecial: false, isArbitrary: false, class: 'const', value: { unit: '[c].a_j', value: '1' } },
  { code: 'gf', name: 'gram-force', property: 'force', isMetric: true, isSpecial: false, isArbitrary: false, class: 'const', value: { unit: 'g.[g]', value: '1' } },
  { code: '[lbf_av]', name: 'pound force', property: 'force', isMetric: false, isSpecial: false, isArbitrary: false, class: 'const', value: { unit: '[lb_av].[g]', value: '1' } },
  { code: 'Ky', name: 'Kayser', property: 'lineic number', isMetric: true, isSpecial: false, isArbitrary: false, class: 'cgs', value: { unit: 'cm-1', value: '1' } },
  { code: 'Gal', name: 'Gal', property: 'acceleration', isMetric: true, isSpecial: false, isArbitrary: false, class: 'cgs', value: { unit: 'cm/s2', value: '1' } },
  { code: 'dyn', name: 'dyne', property: 'force', isMetric: true, isSpecial: false, isArbitrary: false, class: 'cgs', value: { unit: 'g.cm/s2', value: '1' } },
  { code: 'erg', name: 'erg', property: 'energy', isMetric: true, isSpecial: false, isArbitrary: false, class: 'cgs', value: { unit: 'dyn.cm', value: '1' } },
  { code: 'P', name: 'Poise', property: 'dynamic viscosity', isMetric: true, isSpecial: false, isArbitrary: false, class: 'cgs', value: { unit: 'dyn.s/cm2', value: '1' } },
  { code: 'Bi', name: 'Biot', property: 'electric current', isMetric: true, isSpecial: false, isArbitrary: false, class: 'cgs', value: { unit: 'A', value: '10' } },
  { code: 'St', name: 'Stokes', property: 'kinematic viscosity', isMetric: true, isSpecial: false, isArbitrary: false, class: 'cgs', value: { unit: 'cm2/s', value: '1' } },
  { code: 'Mx', name: 'Maxwell', property: 'flux of magnetic induction', isMetric: true, isSpecial: false, isArbitrary: false, class: 'cgs', value: { unit: 'Wb', value: '1e-8' } },
  { code: 'G', name: 'Gauss', property: 'magnetic flux density', isMetric: true, isSpecial: false, isArbitrary: false, class: 'cgs', value: { unit: 'T', value: '1e-4' } },
  { code: 'Oe', name: 'Oersted', property: 'magnetic field intensity', isMetric: true, isSpecial: false, isArbitrary: false, class: 'cgs', value: { unit: '/[pi].A/m', value: '250' } },
  { code: 'Gb', name: 'Gilbert', property: 'magnetic tension', isMetric: true, isSpecial: false, isArbitrary: false, class: 'cgs', value: { unit: 'Oe.cm', value: '1' } },
  { code: 'sb', name: 'stilb', property: 'lum. intensity density', isMetric: true, isSpecial: false, isArbitrary: false, class: 'cgs', value: { unit: 'cd/cm2', value: '1' } },
  { code: 'Lmb', name: 'Lambert', property: 'brightness', isMetric: true, isSpecial: false, isArbitrary: false, class: 'cgs', value: { unit: 'cd/cm2/[pi]', value: '1' } },
  { code: 'ph', name: 'phot', property: 'illuminance', isMetric: true, isSpecial: false, isArbitrary: false, class: 'cgs', value: { unit: 'lx', value: '1e-4' } },
  { code: 'Ci', name: 'Curie', property: 'radioactivity', isMetric: true, isSpecial: false, isArbitrary: false, class: 'cgs', value: { unit: 'Bq', value: '37e9' } },
  { code: 'R', name: 'Roentgen', property: 'ion dose', isMetric: true, isSpecial: false, isArbitrary: false, class: 'cgs', value: { unit: 'C/kg', value: '2.58e-4' } },
  { code: 'RAD', name: 'radiation absorbed dose', property: 'energy dose', isMetric: true, isSpecial: false, isArbitrary: false, class: 'cgs', value: { unit: 'erg/g', value: '100' } },
  { code: 'REM', name: 'radiation equivalent man', property: 'dose equivalent', isMetric: true, isSpecial: false, isArbitrary: false, class: 'cgs', value: { unit: 'RAD', value: '1' } },
  { code: '[in_i]', name: 'inch', property: 'length', isMetric: false, isSpecial: false, isArbitrary: false, class: 'intcust', value: { unit: 'cm', value: '254e-2' } },
  { code: '[ft_i]', name: 'foot', property: 'length', isMetric: false, isSpecial: false, isArbitrary: false, class: 'intcust', value: { unit: '[in_i]', value: '12' } },
  { code: '[yd_i]', name: 'yard', property: 'length', isMetric: false, isSpecial: false, isArbitrary: false, class: 'intcust', value: { unit: '[ft_i]', value: '3' } },
  { code: '[mi_i]', name: 'mile', property: 'length', isMetric: false, isSpecial: false, isArbitrary: false, class: 'intcust', value: { unit: '[ft_i]', value: '5280' } },
  { code: '[fth_i]', name: 'fathom', property: 'depth of water', isMetric: false, isSpecial: false, isArbitrary: false, class: 'intcust', value: { unit: '[ft_i]', value: '6' } },
  { code: '[nmi_i]', name: 'nautical mile', property: 'length', isMetric: false, isSpecial: false, isArbitrary: false, class: 'intcust', value: { unit: 'm', value: '1852' } },
  { code: '[kn_i]', name: 'knot', property: 'velocity', isMetric: false, isSpecial: false, isArbitrary: false, class: 'intcust', value: { unit: '[nmi_i]/h', value: '1' } },
  { code: '[sin_i]', name: 'square inch', property: 'area', isMetric: false, isSpecial: false, isArbitrary: false, class: 'intcust', value: { unit: '[in_i]2', value: '1' } },
  { code: '[sft_i]', name: 'square foot', property: 'area', isMetric: false, isSpecial: false, isArbitrary: false, class: 'intcust', value: { unit: '[ft_i]2', value: '1' } },
  { code: '[syd_i]', name: 'square yard', property: 'area', isMetric: false, isSpecial: false, isArbitrary: false, class: 'intcust', value: { unit: '[yd_i]2', value: '1' } },
  { code: '[cin_i]', name: 'cubic inch', property: 'volume', isMetric: false, isSpecial: false, isArbitrary: false, class: 'intcust', value: { unit: '[in_i]3', value: '1' } },
  { code: '[cft_i]', name: 'cubic foot', property: 'volume', isMetric: false, isSpecial: false, isArbitrary: false, class: 'intcust', value: { unit: '[ft_i]3', value: '1' } },
  { code: '[cyd_i]', name: 'cubic yard', property: 'volume', isMetric: false, isSpecial: false, isArbitrary: false, class: 'intcust', value: { unit: '[yd_i]3', value: '1' } },
  { code: '[bf_i]', name: 'board foot', property: 'volume', isMetric: false, isSpecial: false, isArbitrary: false, class: 'intcust', value: { unit: '[in_i]3', value: '144' } },
  { code: '[cr_i]', name: 'cord', property: 'volume', isMetric: false, isSpecial: false, isArbitrary: false, class: 'intcust', value: { unit: '[ft_i]3', value: '128' } },
  { code: '[mil_i]', name: 'mil', property: 'length', isMetric: false, isSpecial: false, isArbitrary: false, class: 'intcust', value: { unit: '[in_i]', value: '1e-3' } },
  { code: '[cml_i]', name: 'circular mil', property: 'area', isMetric: false, isSpecial: false, isArbitrary: false, class: 'intcust', value: { unit: '[pi]/4.[mil_i]2', value: '1' } },
  { code: '[hd_i]', name: 'hand', property: 'height of horses', isMetric: false, isSpecial: false, isArbitrary: false, class: 'intcust', value: { unit: '[in_i]', value: '4' } },
  { code: '[ft_us]', name: 'foot', property: 'length', isMetric: false, isSpecial: false, isArbitrary: false, class: 'us-lengths', value: { unit: 'm/3937', value: '1200' } },
  { code: '[yd_us]', name: 'yard', property: 'length', isMetric: false, isSpecial: false, isArbitrary: false, class: 'us-lengths', value: { unit: '[ft_us]', value: '3' } },
  { code: '[in_us]', name: 'inch', property: 'length', isMetric: false, isSpecial: false, isArbitrary: false, class: 'us-lengths', value: { unit: '[ft_us]/12', value: '1' } },
  { code: '[rd_us]', name: 'rod', property: 'length', isMetric: false, isSpecial: false, isArbitrary: false, class: 'us-lengths', value: { unit: '[ft_us]', value: '16.5' } },
  { code: '[ch_us]', name: 'Gunter\'s chain', property: 'length', isMetric: false, isSpecial: false, isArbitrary: false, class: 'us-lengths', value: { unit: '[rd_us]', value: '4' } },
  { code: '[lk_us]', name: 'link for Gunter\'s chain', property: 'length', isMetric: false, isSpecial: false, isArbitrary: false, class: 'us-lengths', value: { unit: '[ch_us]/100', value: '1' } },
  { code: '[rch_us]', name: 'Ramden\'s chain', property: 'length', isMetric: false, isSpecial: false, isArbitrary: false, class: 'us-lengths', value: { unit: '[ft_us]', value: '100' } },
  { code: '[rlk_us]', name: 'link for Ramden\'s chain', property: 'length', isMetric: false, isSpecial: false, isArbitrary: false, class: 'us-lengths', value: { unit: '[rch_us]/100', value: '1' } },
  { code: '[fth_us]', name: 'fathom', property: 'length', isMetric: false, isSpecial: false, isArbitrary: false, class: 'us-lengths', value: { unit: '[ft_us]', value: '6' } },
  { code: '[fur_us]', name: 'furlong', property: 'length', isMetric: false, isSpecial: false, isArbitrary: false, class: 'us-lengths', value: { unit: '[rd_us]', value: '40' } },
  { code: '[mi_us]', name: 'mile', property: 'length', isMetric: false, isSpecial: false, isArbitrary: false, class: 'us-lengths', value: { unit: '[fur_us]', value: '8' } },
  { code: '[acr_us]', name: 'acre', property: 'area', isMetric: false, isSpecial: false, isArbitrary: false, class: 'us-lengths', value: { unit: '[rd_us]2', value: '160' } },
  { code: '[srd_us]', name: 'square rod', property: 'area', isMetric: false, isSpecial: false, isArbitrary: false, class: 'us-lengths', value: { unit: '[rd_us]2', value: '1' } },
  { code: '[smi_us]', name: 'square mile', property: 'area', isMetric: false, isSpecial: false, isArbitrary: false, class: 'us-lengths', value: { unit: '[mi_us]2', value: '1' } },
  { code: '[sct]', name: 'section', property: 'area', isMetric: false, isSpecial: false, isArbitrary: false, class: 'us-lengths', value: { unit: '[mi_us]2', value: '1' } },
  { code: '[twp]', name: 'township', property: 'area', isMetric: false, isSpecial: false, isArbitrary: false, class: 'us-lengths', value: { unit: '[sct]', value: '36' } },
  { code: '[mil_us]', name: 'mil', property: 'length', isMetric: false, isSpecial: false, isArbitrary: false, class: 'us-lengths', value: { unit: '[in_us]', value: '1e-3' } },
  { code: '[in_br]', name: 'inch', property: 'length', isMetric: false, isSpecial: false, isArbitrary: false, class: 'brit-length', value: { unit: 'cm', value: '2.539998' } },
  { code: '[ft_br]', name: 'foot', property: 'length', isMetric: false, isSpecial: false, isArbitrary: false, class: 'brit-length', value: { unit: '[in_br]', value: '12' } },
  { code: '[rd_br]', name: 'rod', property: 'length', isMetric: false, isSpecial: false, isArbitrary: false, class: 'brit-length', value: { unit: '[ft_br]', value: '16.5' } },
  { code: '[ch_br]', name: 'Gunter\'s chain', property: 'length', isMetric: false, isSpecial: false, isArbitrary: false, class: 'brit-length', value: { unit: '[rd_br]', value: '4' } },
  { code: '[lk_br]', name: 'link for Gunter\'s chain', property: 'length', isMetric: false, isSpecial: false, isArbitrary: false, class: 'brit-length', value: { unit: '[ch_br]/100', value: '1' } },
  { code: '[fth_br]', name: 'fathom', property: 'length', isMetric: false, isSpecial: false, isArbitrary: false, class: 'brit-length', value: { unit: '[ft_br]', value: '6' } },
  { code: '[pc_br]', name: 'pace', property: 'length', isMetric: false, isSpecial: false, isArbitrary: false, class: 'brit-length', value: { unit: '[ft_br]', value: '2.5' } },
  { code: '[yd_br]', name: 'yard', property: 'length', isMetric: false, isSpecial: false, isArbitrary: false, class: 'brit-length', value: { unit: '[ft_br]', value: '3' } },
  { code: '[mi_br]', name: 'mile', property: 'length', isMetric: false, isSpecial: false, isArbitrary: false, class: 'brit-length', value: { unit: '[ft_br]', value: '5280' } },
  { code: '[nmi_br]', name: 'nautical mile', property: 'length', isMetric: false, isSpecial: false, isArbitrary: false, class: 'brit-length', value: { unit: '[ft_br]', value: '6080' } },
  { code: '[kn_br]', name: 'knot', property: 'velocity', isMetric: false, isSpecial: false, isArbitrary: false, class: 'brit-length', value: { unit: '[nmi_br]/h', value: '1' } },
  { code: '[acr_br]', name: 'acre', property: 'area', isMetric: false, isSpecial: false, isArbitrary: false, class: 'brit-length', value: { unit: '[yd_br]2', value: '4840' } },
  { code: '[gal_us]', name: 'Queen Anne\'s wine gallon', property: 'fluid volume', isMetric: false, isSpecial: false, isArbitrary: false, class: 'us-volumes', value: { unit: '[in_i]3', value: '231' } },
  { code: '[bbl_us]', name: 'barrel', property: 'fluid volume', isMetric: false, isSpecial: false, isArbitrary: false, class: 'us-volumes', value: { unit: '[gal_us]', value: '42' } },
  { code: '[qt_us]', name: 'quart', property: 'fluid volume', isMetric: false, isSpecial: false, isArbitrary: false, class: 'us-volumes', value: { unit: '[gal_us]/4', value: '1' } },
  { code: '[pt_us]', name: 'pint', property: 'fluid volume', isMetric: false, isSpecial: false, isArbitrary: false, class: 'us-volumes', value: { unit: '[qt_us]/2', value: '1' } },
  { code: '[gil_us]', name: 'gill', property: 'fluid volume', isMetric: false, isSpecial: false, isArbitrary: false, class: 'us-volumes', value: { unit: '[pt_us]/4', value: '1' } },
  { code: '[foz_us]', name: 'fluid ounce', property: 'fluid volume', isMetric: false, isSpecial: false, isArbitrary: false, class: 'us-volumes', value: { unit: '[gil_us]/4', value: '1' } },
  { code: '[fdr_us]', name: 'fluid dram', property: 'fluid volume', isMetric: false, isSpecial: false, isArbitrary: false, class: 'us-volumes', value: { unit: '[foz_us]/8', value: '1' } },
  { code: '[min_us]', name: 'minim', property: 'fluid volume', isMetric: false, isSpecial: false, isArbitrary: false, class: 'us-volumes', value: { unit: '[fdr_us]/60', value: '1' } },
  { code: '[crd_us]', name: 'cord', property: 'fluid volume', isMetric: false, isSpecial: false, isArbitrary: false, class: 'us-volumes', value: { unit: '[ft_i]3', value: '128' } },
  { code: '[bu_us]', name: 'bushel', property: 'dry volume', isMetric: false, isSpecial: false, isArbitrary: false, class: 'us-volumes', value: { unit: '[in_i]3', value: '2150.42' } },
  { code: '[gal_wi]', name: 'historical winchester gallon', property: 'dry volume', isMetric: false, isSpecial: false, isArbitrary: false, class: 'us-volumes', value: { unit: '[bu_us]/8', value: '1' } },
  { code: '[pk_us]', name: 'peck', property: 'dry volume', isMetric: false, isSpecial: false, isArbitrary: false, class: 'us-volumes', value: { unit: '[bu_us]/4', value: '1' } },
  { code: '[dqt_us]', name: 'dry quart', property: 'dry volume', isMetric: false, isSpecial: false, isArbitrary: false, class: 'us-volumes', value: { unit: '[pk_us]/8', value: '1' } },
  { code: '[dpt_us]', name: 'dry pint', property: 'dry volume', isMetric: false, isSpecial: false, isArbitrary: false, class: 'us-volumes', value: { unit: '[dqt_us]/2', value: '1' } },
  { code: '[tbs_us]', name: 'tablespoon', property: 'volume', isMetric: false, isSpecial: false, isArbitrary: false, class: 'us-volumes', value: { unit: '[foz_us]/2', value: '1' } },
  { code: '[tsp_us]', name: 'teaspoon', property: 'volume', isMetric: false, isSpecial: false, isArbitrary: false, class: 'us-volumes', value: { unit: '[tbs_us]/3', value: '1' } },
  { code: '[cup_us]', name: 'cup', property: 'volume', isMetric: false, isSpecial: false, isArbitrary: false, class: 'us-volumes', value: { unit: '[tbs_us]', value: '16' } },
  { code: '[foz_m]', name: 'metric fluid ounce', property: 'fluid volume', isMetric: false, isSpecial: false, isArbitrary: false, class: 'us-volumes', value: { unit: 'mL', value: '30' } },
  { code: '[cup_m]', name: 'metric cup', property: 'volume', isMetric: false, isSpecial: false, isArbitrary: false, class: 'us-volumes', value: { unit: 'mL', value: '240' } },
  { code: '[tsp_m]', name: 'metric teaspoon', property: 'volume', isMetric: false, isSpecial: false, isArbitrary: false, class: 'us-volumes', value: { unit: 'mL', value: '5' } },
  { code: '[tbs_m]', name: 'metric tablespoon', property: 'volume', isMetric: false, isSpecial: false, isArbitrary: false, class: 'us-volumes', value: { unit: 'mL', value: '15' } },
  { code: '[gal_br]', name: 'gallon', property: 'volume', isMetric: false, isSpecial: false, isArbitrary: false, class: 'brit-volumes', value: { unit: 'l', value: '4.54609' } },
  { code: '[pk_br]', name: 'peck', property: 'volume', isMetric: false, isSpecial: false, isArbitrary: false, class: 'brit-volumes', value: { unit: '[gal_br]', value: '2' } },
  { code: '[bu_br]', name: 'bushel', property: 'volume', isMetric: false, isSpecial: false, isArbitrary: false, class: 'brit-volumes', value: { unit: '[pk_br]', value: '4' } },
  { code: '[qt_br]', name: 'quart', property: 'volume', isMetric: false, isSpecial: false, isArbitrary: false, class: 'brit-volumes', value: { unit: '[gal_br]/4', value: '1' } },
  { code: '[pt_br]', name: 'pint', property: 'volume', isMetric: false, isSpecial: false, isArbitrary: false, class: 'brit-volumes', value: { unit: '[qt_br]/2', value: '1' } },
  { code: '[gil_br]', name: 'gill', property: 'volume', isMetric: false, isSpecial: false, isArbitrary: false, class: 'brit-volumes', value: { unit: '[pt_br]/4', value: '1' } },
  { code: '[foz_br]', name: 'fluid ounce', property: 'volume', isMetric: false, isSpecial: false, isArbitrary: false, class: 'brit-volumes', value: { unit: '[gil_br]/5', value: '1' } },
  { code: '[fdr_br]', name: 'fluid dram', property: 'volume', isMetric: false, isSpecial: false, isArbitrary: false, class: 'brit-volumes', value: { unit: '[foz_br]/8', value: '1' } },
  { code: '[min_br]', name: 'minim', property: 'volume', isMetric: false, isSpecial: false, isArbitrary: false, class: 'brit-volumes', value: { unit: '[fdr_br]/60', value: '1' } },
  { code: '[gr]', name: 'grain', property: 'mass', isMetric: false, isSpecial: false, isArbitrary: false, class: 'avoirdupois', value: { unit: 'mg', value: '64.79891' } },
  { code: '[lb_av]', name: 'pound', property: 'mass', isMetric: false, isSpecial: false, isArbitrary: false, class: 'avoirdupois', value: { unit: '[gr]', value: '7000' } },
  { code: '[oz_av]', name: 'ounce', property: 'mass', isMetric: false, isSpecial: false, isArbitrary: false, class: 'avoirdupois', value: { unit: '[lb_av]/16', value: '1' } },
  { code: '[dr_av]', name: 'dram', property: 'mass', isMetric: false, isSpecial: false, isArbitrary: false, class: 'avoirdupois', value: { unit: '[oz_av]/16', value: '1' } },
  { code: '[scwt_av]', name: 'short hundredweight', property: 'mass', isMetric: false, isSpecial: false, isArbitrary: false, class: 'avoirdupois', value: { unit: '[lb_av]', value: '100' } },
  { code: '[lcwt_av]', name: 'long hundredweight', property: 'mass', isMetric: false, isSpecial: false, isArbitrary: false, class: 'avoirdupois', value: { unit: '[lb_av]', value: '112' } },
  { code: '[ston_av]', name: 'short ton', property: 'mass', isMetric: false, isSpecial: false, isArbitrary: false, class: 'avoirdupois', value: { unit: '[scwt_av]', value: '20' } },
  { code: '[lton_av]', name: 'long ton', property: 'mass', isMetric: false, isSpecial: false, isArbitrary: false, class: 'avoirdupois', value: { unit: '[lcwt_av]', value: '20' } },
  { code: '[stone_av]', name: 'stone', property: 'mass', isMetric: false, isSpecial: false, isArbitrary: false, class: 'avoirdupois', value: { unit: '[lb_av]', value: '14' } },
  { code: '[pwt_tr]', name: 'pennyweight', property: 'mass', isMetric: false, isSpecial: false, isArbitrary: false, class: 'troy', value: { unit: '[gr]', value: '24' } },
  { code: '[oz_tr]', name: 'ounce', property: 'mass', isMetric: false, isSpecial: false, isArbitrary: false, class: 'troy', value: { unit: '[pwt_tr]', value: '20' } },
  { code: '[lb_tr]', name: 'pound', property: 'mass', isMetric: false, isSpecial: false, isArbitrary: false, class: 'troy', value: { unit: '[oz_tr]', value: '12' } },
  { code: '[sc_ap]', name: 'scruple', property: 'mass', isMetric: false, isSpecial: false, isArbitrary: false, class: 'apoth', value: { unit: '[gr]', value: '20' } },
  { code: '[dr_ap]', name: 'dram', property: 'mass', isMetric: false, isSpecial: false, isArbitrary: false, class: 'apoth', value: { unit: '[sc_ap]', value: '3' } },
  { code: '[oz_ap]', name: 'ounce', property: 'mass', isMetric: false, isSpecial: false, isArbitrary: false, class: 'apoth', value: { unit: '[dr_ap]', value: '8' } },
  { code: '[lb_ap]', name: 'pound', property: 'mass', isMetric: false, isSpecial: false, isArbitrary: false, class: 'apoth', value: { unit: '[oz_ap]', value: '12' } },
  { code: '[oz_m]', name: 'metric ounce', property: 'mass', isMetric: false, isSpecial: false, isArbitrary: false, class: 'apoth', value: { unit: 'g', value: '28' } },
  { code: '[lne]', name: 'line', property: 'length', isMetric: false, isSpecial: false, isArbitrary: false, class: 'typeset', value: { unit: '[in_i]/12', value: '1' } },
  { code: '[pnt]', name: 'point', property: 'length', isMetric: false, isSpecial: false, isArbitrary: false, class: 'typeset', value: { unit: '[lne]/6', value: '1' } },
  { code: '[pca]', name: 'pica', property: 'length', isMetric: false, isSpecial: false, isArbitrary: false, class: 'typeset', value: { unit: '[pnt]', value: '12' } },
  { code: '[pnt_pr]', name: 'Printer\'s point', property: 'length', isMetric: false, isSpecial: false, isArbitrary: false, class: 'typeset', value: { unit: '[in_i]', value: '0.013837' } },
  { code: '[pca_pr]', name: 'Printer\'s pica', property: 'length', isMetric: false, isSpecial: false, isArbitrary: false, class: 'typeset', value: { unit: '[pnt_pr]', value: '12' } },
  { code: '[pied]', name: 'pied', property: 'length', isMetric: false, isSpecial: false, isArbitrary: false, class: 'typeset', value: { unit: 'cm', value: '32.48' } },
  { code: '[pouce]', name: 'pouce', property: 'length', isMetric: false, isSpecial: false, isArbitrary: false, class: 'typeset', value: { unit: '[pied]/12', value: '1' } },
  { code: '[ligne]', name: 'ligne', property: 'length', isMetric: false, isSpecial: false, isArbitrary: false, class: 'typeset', value: { unit: '[pouce]/12', value: '1' } },
  { code: '[didot]', name: 'didot', property: 'length', isMetric: false, isSpecial: false, isArbitrary: false, class: 'typeset', value: { unit: '[ligne]/6', value: '1' } },
  { code: '[cicero]', name: 'cicero', property: 'length', isMetric: false, isSpecial: false, isArbitrary: false, class: 'typeset', value: { unit: '[didot]', value: '12' } },
  { code: '[degF]', name: 'degree Fahrenheit', property: 'temperature', isMetric: false, isSpecial: true, isArbitrary: false, class: 'heat', value: { unit: 'degf(5 K/9)', value: '' } },
  { code: '[degR]', name: 'degree Rankine', property: 'temperature', isMetric: false, isSpecial: false, isArbitrary: false, class: 'heat', value: { unit: 'K/9', value: '5' } },
  { code: '[degRe]', name: 'degree Réaumur', property: 'temperature', isMetric: false, isSpecial: true, isArbitrary: false, class: 'heat', value: { unit: 'degre(5 K/4)', value: '' } },
  { code: 'cal_[15]', name: 'calorie at 15 °C', property: 'energy', isMetric: true, isSpecial: false, isArbitrary: false, class: 'heat', value: { unit: 'J', value: '4.18580' } },
  { code: 'cal_[20]', name: 'calorie at 20 °C', property: 'energy', isMetric: true, isSpecial: false, isArbitrary: false, class: 'heat', value: { unit: 'J', value: '4.18190' } },
  { code: 'cal_m', name: 'mean calorie', property: 'energy', isMetric: true, isSpecial: false, isArbitrary: false, class: 'heat', value: { unit: 'J', value: '4.19002' } },
  { code: 'cal_IT', name: 'international table calorie', property: 'energy', isMetric: true, isSpecial: false, isArbitrary: false, class: 'heat', value: { unit: 'J', value: '4.1868' } },
  { code: 'cal_th', name: 'thermochemical calorie', property: 'energy', isMetric: true, isSpecial: false, isArbitrary: false, class: 'heat', value: { unit: 'J', value: '4.184' } },
  { code: 'cal', name: 'calorie', property: 'energy', isMetric: true, isSpecial: false, isArbitrary: false, class: 'heat', value: { unit: 'cal_th', value: '1' } },
  { code: '[Cal]', name: 'nutrition label Calories', property: 'energy', isMetric: false, isSpecial: false, isArbitrary: false, class: 'heat', value: { unit: 'kcal_th', value: '1' } },
  { code: '[Btu_39]', name: 'British thermal unit at 39 °F', property: 'energy', isMetric: false, isSpecial: false, isArbitrary: false, class: 'heat', value: { unit: 'kJ', value: '1.05967' } },
  { code: '[Btu_59]', name: 'British thermal unit at 59 °F', property: 'energy', isMetric: false, isSpecial: false, isArbitrary: false, class: 'heat', value: { unit: 'kJ', value: '1.05480' } },
  { code: '[Btu_60]', name: 'British thermal unit at 60 °F', property: 'energy', isMetric: false, isSpecial: false, isArbitrary: false, class: 'heat', value: { unit: 'kJ', value: '1.05468' } },
  { code: '[Btu_m]', name: 'mean British thermal unit', property: 'energy', isMetric: false, isSpecial: false, isArbitrary: false, class: 'heat', value: { unit: 'kJ', value: '1.05587' } },
  { code: '[Btu_IT]', name: 'international table British thermal unit', property: 'energy', isMetric: false, isSpecial: false, isArbitrary: false, class: 'heat', value: { unit: 'kJ', value: '1.05505585262' } },
  { code: '[Btu_th]', name: 'thermochemical British thermal unit', property: 'energy', isMetric: false, isSpecial: false, isArbitrary: false, class: 'heat', value: { unit: 'kJ', value: '1.054350' } },
  { code: '[Btu]', name: 'British thermal unit', property: 'energy', isMetric: false, isSpecial: false, isArbitrary: false, class: 'heat', value: { unit: '[Btu_th]', value: '1' } },
  { code: '[HP]', name: 'horsepower', property: 'power', isMetric: false, isSpecial: false, isArbitrary: false, class: 'heat', value: { unit: '[ft_i].[lbf_av]/s', value: '550' } },
  { code: 'tex', name: 'tex', property: 'linear mass density (of textile thread)', isMetric: true, isSpecial: false, isArbitrary: false, class: 'heat', value: { unit: 'g/km', value: '1' } },
  { code: '[den]', name: 'Denier', property: 'linear mass density (of textile thread)', isMetric: false, isSpecial: false, isArbitrary: false, class: 'heat', value: { unit: 'g/9/km', value: '1' } },
  { code: 'm[H2O]', name: 'meter of water column', property: 'pressure', isMetric: true, isSpecial: false, isArbitrary: false, class: 'clinical', value: { unit: 'kPa', value: '980665e-5' } },
  { code: 'm[Hg]', name: 'meter of mercury column', property: 'pressure', isMetric: true, isSpecial: false, isArbitrary: false, class: 'clinical', value: { unit: 'kPa', value: '133.3220' } },
  { code: '[in_i\'H2O]', name: 'inch of water column', property: 'pressure', isMetric: false, isSpecial: false, isArbitrary: false, class: 'clinical', value: { unit: 'm[H2O].[in_i]/m', value: '1' } },
  { code: '[in_i\'Hg]', name: 'inch of mercury column', property: 'pressure', isMetric: false, isSpecial: false, isArbitrary: false, class: 'clinical', value: { unit: 'm[Hg].[in_i]/m', value: '1' } },
  { code: '[PRU]', name: 'peripheral vascular resistance unit', property: 'fluid resistance', isMetric: false, isSpecial: false, isArbitrary: false, class: 'clinical', value: { unit: 'mm[Hg].s/ml', value: '1' } },
  { code: '[wood\'U]', name: 'Wood unit', property: 'fluid resistance', isMetric: false, isSpecial: false, isArbitrary: false, class: 'clinical', value: { unit: 'mm[Hg].min/L', value: '1' } },
  { code: '[diop]', name: 'diopter', property: 'refraction of a lens', isMetric: false, isSpecial: false, isArbitrary: false, class: 'clinical', value: { unit: '/m', value: '1' } },
  { code: '[p\'diop]', name: 'prism diopter', property: 'refraction of a prism', isMetric: false, isSpecial: true, isArbitrary: false, class: 'clinical', value: { unit: '100tan(1 rad)', value: '' } },
  { code: '%[slope]', name: 'percent of slope', property: 'slope', isMetric: false, isSpecial: true, isArbitrary: false, class: 'clinical', value: { unit: '100tan(1 rad)', value: '' } },
  { code: '[mesh_i]', name: 'mesh', property: 'lineic number', isMetric: false, isSpecial: false, isArbitrary: false, class: 'clinical', value: { unit: '/[in_i]', value: '1' } },
  { code: '[Ch]', name: 'Charrière', property: 'gauge of catheters', isMetric: false, isSpecial: false, isArbitrary: false, class: 'clinical', value: { unit: 'mm/3', value: '1' } },
  { code: '[drp]', name: 'drop', property: 'volume', isMetric: false, isSpecial: false, isArbitrary: false, class: 'clinical', value: { unit: 'ml/20', value: '1' } },
  { code: '[hnsf\'U]', name: 'Hounsfield unit', property: 'x-ray attenuation', isMetric: false, isSpecial: false, isArbitrary: false, class: 'clinical', value: { unit: '1', value: '1' } },
  { code: '[MET]', name: 'metabolic equivalent', property: 'metabolic cost of physical activity', isMetric: false, isSpecial: false, isArbitrary: false, class: 'clinical', value: { unit: 'mL/min/kg', value: '3.5' } },
  { code: '[hp\'_X]', name: 'homeopathic potency of decimal series (retired)', property: 'homeopathic potency (retired)', isMetric: false, isSpecial: true, isArbitrary: false, class: 'clinical', value: { unit: 'hpX(1 1)', value: '' } },
  { code: '[hp\'_C]', name: 'homeopathic potency of centesimal series (retired)', property: 'homeopathic potency (retired)', isMetric: false, isSpecial: true, isArbitrary: false, class: 'clinical', value: { unit: 'hpC(1 1)', value: '' } },
  { code: '[hp\'_M]', name: 'homeopathic potency of millesimal series (retired)', property: 'homeopathic potency (retired)', isMetric: false, isSpecial: true, isArbitrary: false, class: 'clinical', value: { unit: 'hpM(1 1)', value: '' } },
  { code: '[hp\'_Q]', name: 'homeopathic potency of quintamillesimal series (retired)', property: 'homeopathic potency (retired)', isMetric: false, isSpecial: true, isArbitrary: false, class: 'clinical', value: { unit: 'hpQ(1 1)', value: '' } },
  { code: '[hp_X]', name: 'homeopathic potency of decimal hahnemannian series', property: 'homeopathic potency (Hahnemann)', isMetric: false, isSpecial: false, isArbitrary: true, class: 'clinical', value: { unit: '1', value: '1' } },
  { code: '[hp_C]', name: 'homeopathic potency of centesimal hahnemannian series', property: 'homeopathic potency (Hahnemann)', isMetric: false, isSpecial: false, isArbitrary: true, class: 'clinical', value: { unit: '1', value: '1' } },
  { code: '[hp_M]', name: 'homeopathic potency of millesimal hahnemannian series', property: 'homeopathic potency (Hahnemann)', isMetric: false, isSpecial: false, isArbitrary: true, class: 'clinical', value: { unit: '1', value: '1' } },
  { code: '[hp_Q]', name: 'homeopathic potency of quintamillesimal hahnemannian series', property: 'homeopathic potency (Hahnemann)', isMetric: false, isSpecial: false, isArbitrary: true, class: 'clinical', value: { unit: '1', value: '1' } },
  { code: '[kp_X]', name: 'homeopathic potency of decimal korsakovian series', property: 'homeopathic potency (Korsakov)', isMetric: false, isSpecial: false, isArbitrary: true, class: 'clinical', value: { unit: '1', value: '1' } },
  { code: '[kp_C]', name: 'homeopathic potency of centesimal korsakovian series', property: 'homeopathic potency (Korsakov)', isMetric: false, isSpecial: false, isArbitrary: true, class: 'clinical', value: { unit: '1', value: '1' } },
  { code: '[kp_M]', name: 'homeopathic potency of millesimal korsakovian series', property: 'homeopathic potency (Korsakov)', isMetric: false, isSpecial: false, isArbitrary: true, class: 'clinical', value: { unit: '1', value: '1' } },
  { code: '[kp_Q]', name: 'homeopathic potency of quintamillesimal korsakovian series', property: 'homeopathic potency (Korsakov)', isMetric: false, isSpecial: false, isArbitrary: true, class: 'clinical', value: { unit: '1', value: '1' } },
  { code: 'eq', name: 'equivalents', property: 'amount of substance', isMetric: true, isSpecial: false, isArbitrary: false, class: 'chemical', value: { unit: 'mol', value: '1' } },
  { code: 'osm', name: 'osmole', property: 'amount of substance (dissolved particles)', isMetric: true, isSpecial: false, isArbitrary: false, class: 'chemical', value: { unit: 'mol', value: '1' } },
  { code: '[pH]', name: 'pH', property: 'acidity', isMetric: false, isSpecial: true, isArbitrary: false, class: 'chemical', value: { unit: 'pH(1 mol/l)', value: '' } },
  { code: 'g%', name: 'gram percent', property: 'mass concentration', isMetric: true, isSpecial: false, isArbitrary: false, class: 'chemical', value: { unit: 'g/dl', value: '1' } },
  { code: '[S]', name: 'Svedberg unit', property: 'sedimentation coefficient', isMetric: false, isSpecial: false, isArbitrary: false, class: 'chemical', value: { unit: '10*-13.s', value: '1' } },
  { code: '[HPF]', name: 'high power field', property: 'view area in microscope', isMetric: false, isSpecial: false, isArbitrary: false, class: 'chemical', value: { unit: '1', value: '1' } },
  { code: '[LPF]', name: 'low power field', property: 'view area in microscope', isMetric: false, isSpecial: false, isArbitrary: false, class: 'chemical', value: { unit: '1', value: '100' } },
  { code: 'kat', name: 'katal', property: 'catalytic activity', isMetric: true, isSpecial: false, isArbitrary: false, class: 'chemical', value: { unit: 'mol/s', value: '1' } },
  { code: 'U', name: 'Unit', property: 'catalytic activity', isMetric: true, isSpecial: false, isArbitrary: false, class: 'chemical', value: { unit: 'umol/min', value: '1' } },
  { code: '[iU]', name: 'international unit', property: 'arbitrary', isMetric: true, isSpecial: false, isArbitrary: true, class: 'chemical', value: { unit: '1', value: '1' } },
  { code: '[IU]', name: 'international unit', property: 'arbitrary', isMetric: true, isSpecial: false, isArbitrary: true, class: 'chemical', value: { unit: '[iU]', value: '1' } },
  { code: '[arb\'U]', name: 'arbitrary unit', property: 'arbitrary', isMetric: false, isSpecial: false, isArbitrary: true, class: 'chemical', value: { unit: '1', value: '1' } },
  { code: '[USP\'U]', name: 'United States Pharmacopeia unit', property: 'arbitrary', isMetric: false, isSpecial: false, isArbitrary: true, class: 'chemical', value: { unit: '1', value: '1' } },
  { code: '[GPL\'U]', name: 'GPL unit', property: 'biologic activity of anticardiolipin IgG', isMetric: false, isSpecial: false, isArbitrary: true, class: 'chemical', value: { unit: '1', value: '1' } },
  { code: '[MPL\'U]', name: 'MPL unit', property: 'biologic activity of anticardiolipin IgM', isMetric: false, isSpecial: false, isArbitrary: true, class: 'chemical', value: { unit: '1', value: '1' } },
  { code: '[APL\'U]', name: 'APL unit', property: 'biologic activity of anticardiolipin IgA', isMetric: false, isSpecial: false, isArbitrary: true, class: 'chemical', value: { unit: '1', value: '1' } },
  { code: '[beth\'U]', name: 'Bethesda unit', property: 'biologic activity of factor VIII inhibitor', isMetric: false, isSpecial: false, isArbitrary: true, class: 'chemical', value: { unit: '1', value: '1' } },
  { code: '[anti\'Xa\'U]', name: 'anti factor Xa unit', property: 'biologic activity of factor Xa inhibitor (heparin)', isMetric: false, isSpecial: false, isArbitrary: true, class: 'chemical', value: { unit: '1', value: '1' } },
  { code: '[todd\'U]', name: 'Todd unit', property: 'biologic activity antistreptolysin O', isMetric: false, isSpecial: false, isArbitrary: true, class: 'chemical', value: { unit: '1', value: '1' } },
  { code: '[dye\'U]', name: 'Dye unit', property: 'biologic activity of amylase', isMetric: false, isSpecial: false, isArbitrary: true, class: 'chemical', value: { unit: '1', value: '1' } },
  { code: '[smgy\'U]', name: 'Somogyi unit', property: 'biologic activity of amylase', isMetric: false, isSpecial: false, isArbitrary: true, class: 'chemical', value: { unit: '1', value: '1' } },
  { code: '[bdsk\'U]', name: 'Bodansky unit', property: 'biologic activity of phosphatase', isMetric: false, isSpecial: false, isArbitrary: true, class: 'chemical', value: { unit: '1', value: '1' } },
  { code: '[ka\'U]', name: 'King-Armstrong unit', property: 'biologic activity of phosphatase', isMetric: false, isSpecial: false, isArbitrary: true, class: 'chemical', value: { unit: '1', value: '1' } },
  { code: '[knk\'U]', name: 'Kunkel unit', property: 'arbitrary biologic activity', isMetric: false, isSpecial: false, isArbitrary: true, class: 'chemical', value: { unit: '1', value: '1' } },
  { code: '[mclg\'U]', name: 'Mac Lagan unit', property: 'arbitrary biologic activity', isMetric: false, isSpecial: false, isArbitrary: true, class: 'chemical', value: { unit: '1', value: '1' } },
  { code: '[tb\'U]', name: 'tuberculin unit', property: 'biologic activity of tuberculin', isMetric: false, isSpecial: false, isArbitrary: true, class: 'chemical', value: { unit: '1', value: '1' } },
  { code: '[CCID_50]', name: '50% cell culture infectious dose', property: 'biologic activity (infectivity) of an infectious agent preparation', isMetric: false, isSpecial: false, isArbitrary: true, class: 'chemical', value: { unit: '1', value: '1' } },
  { code: '[TCID_50]', name: '50% tissue culture infectious dose', property: 'biologic activity (infectivity) of an infectious agent preparation', isMetric: false, isSpecial: false, isArbitrary: true, class: 'chemical', value: { unit: '1', value: '1' } },
  { code: '[EID_50]', name: '50% embryo infectious dose', property: 'biologic activity (infectivity) of an infectious agent preparation', isMetric: false, isSpecial: false, isArbitrary: true, class: 'chemical', value: { unit: '1', value: '1' } },
  { code: '[PFU]', name: 'plaque forming units', property: 'amount of an infectious agent', isMetric: false, isSpecial: false, isArbitrary: true, class: 'chemical', value: { unit: '1', value: '1' } },
  { code: '[FFU]', name: 'focus forming units', property: 'amount of an infectious agent', isMetric: false, isSpecial: false, isArbitrary: true, class: 'chemical', value: { unit: '1', value: '1' } },
  { code: '[CFU]', name: 'colony forming units', property: 'amount of a proliferating organism', isMetric: false, isSpecial: false, isArbitrary: true, class: 'chemical', value: { unit: '1', value: '1' } },
  { code: '[IR]', name: 'index of reactivity', property: 'amount of an allergen calibrated through in-vivo testing using the Stallergenes® method', isMetric: false, isSpecial: false, isArbitrary: true, class: 'chemical', value: { unit: '1', value: '1' } },
  { code: '[BAU]', name: 'bioequivalent allergen unit', property: 'amount of an allergen calibrated through in-vivo testing based on the ID50EAL method of (intradermal dilution for 50mm sum of erythema diameters', isMetric: false, isSpecial: false, isArbitrary: true, class: 'chemical', value: { unit: '1', value: '1' } },
  { code: '[AU]', name: 'allergen unit', property: 'procedure defined amount of an allergen using some reference standard', isMetric: false, isSpecial: false, isArbitrary: true, class: 'chemical', value: { unit: '1', value: '1' } },
  { code: '[Amb\'a\'1\'U]', name: 'allergen unit for Ambrosia artemisiifolia', property: 'procedure defined amount of the major allergen of ragweed', isMetric: false, isSpecial: false, isArbitrary: true, class: 'chemical', value: { unit: '1', value: '1' } },
  { code: '[PNU]', name: 'protein nitrogen unit', property: 'procedure defined amount of a protein substance', isMetric: false, isSpecial: false, isArbitrary: true, class: 'chemical', value: { unit: '1', value: '1' } },
  { code: '[Lf]', name: 'Limit of flocculation', property: 'procedure defined amount of an antigen substance', isMetric: false, isSpecial: false, isArbitrary: true, class: 'chemical', value: { unit: '1', value: '1' } },
  { code: '[D\'ag\'U]', name: 'D-antigen unit', property: 'procedure defined amount of a poliomyelitis d-antigen substance', isMetric: false, isSpecial: false, isArbitrary: true, class: 'chemical', value: { unit: '1', value: '1' } },
  { code: '[FEU]', name: 'fibrinogen equivalent unit', property: 'amount of fibrinogen broken down into the measured d-dimers', isMetric: false, isSpecial: false, isArbitrary: true, class: 'chemical', value: { unit: '1', value: '1' } },
  { code: '[ELU]', name: 'ELISA unit', property: 'arbitrary ELISA unit', isMetric: false, isSpecial: false, isArbitrary: true, class: 'chemical', value: { unit: '1', value: '1' } },
  { code: '[EU]', name: 'Ehrlich unit', property: 'Ehrlich unit', isMetric: false, isSpecial: false, isArbitrary: true, class: 'chemical', value: { unit: '1', value: '1' } },
  { code: 'Np', name: 'neper', property: 'level', isMetric: true, isSpecial: true, isArbitrary: false, class: 'levels', value: { unit: 'ln(1 1)', value: '' } },
  { code: 'B', name: 'bel', property: 'level', isMetric: true, isSpecial: true, isArbitrary: false, class: 'levels', value: { unit: 'lg(1 1)', value: '' } },
  { code: 'B[SPL]', name: 'bel sound pressure', property: 'pressure level', isMetric: true, isSpecial: true, isArbitrary: false, class: 'levels', value: { unit: '2lg(2 10*-5.Pa)', value: '' } },
  { code: 'B[V]', name: 'bel volt', property: 'electric potential level', isMetric: true, isSpecial: true, isArbitrary: false, class: 'levels', value: { unit: '2lg(1 V)', value: '' } },
  { code: 'B[mV]', name: 'bel millivolt', property: 'electric potential level', isMetric: true, isSpecial: true, isArbitrary: false, class: 'levels', value: { unit: '2lg(1 mV)', value: '' } },
  { code: 'B[uV]', name: 'bel microvolt', property: 'electric potential level', isMetric: true, isSpecial: true, isArbitrary: false, class: 'levels', value: { unit: '2lg(1 uV)', value: '' } },
  { code: 'B[10.nV]', name: 'bel 10 nanovolt', property: 'electric potential level', isMetric: true, isSpecial: true, isArbitrary: false, class: 'levels', value: { unit: '2lg(10 nV)', value: '' } },
  { code: 'B[W]', name: 'bel watt', property: 'power level', isMetric: true, isSpecial: true, isArbitrary: false, class: 'levels', value: { unit: 'lg(1 W)', value: '' } },
  { code: 'B[kW]', name: 'bel kilowatt', property: 'power level', isMetric: true, isSpecial: true, isArbitrary: false, class: 'levels', value: { unit: 'lg(1 kW)', value: '' } },
  { code: 'st', name: 'stere', property: 'volume', isMetric: true, isSpecial: false, isArbitrary: false, class: 'misc', value: { unit: 'm3', value: '1' } },
  { code: 'Ao', name: 'Ångström', property: 'length', isMetric: false, isSpecial: false, isArbitrary: false, class: 'misc', value: { unit: 'nm', value: '0.1' } },
  { code: 'b', name: 'barn', property: 'action area', isMetric: false, isSpecial: false, isArbitrary: false, class: 'misc', value: { unit: 'fm2', value: '100' } },
  { code: 'att', name: 'technical atmosphere', property: 'pressure', isMetric: false, isSpecial: false, isArbitrary: false, class: 'misc', value: { unit: 'kgf/cm2', value: '1' } },
  { code: 'mho', name: 'mho', property: 'electric conductance', isMetric: true, isSpecial: false, isArbitrary: false, class: 'misc', value: { unit: 'S', value: '1' } },
  { code: '[psi]', name: 'pound per square inch', property: 'pressure', isMetric: false, isSpecial: false, isArbitrary: false, class: 'misc', value: { unit: '[lbf_av]/[in_i]2', value: '1' } },
  { code: 'circ', name: 'circle', property: 'plane angle', isMetric: false, isSpecial: false, isArbitrary: false, class: 'misc', value: { unit: '[pi].rad', value: '2' } },
  { code: 'sph', name: 'sphere', property: 'solid angle', isMetric: false, isSpecial: false, isArbitrary: false, class: 'misc', value: { unit: '[pi].sr', value: '4' } },
  { code: '[car_m]', name: 'metric carat', property: 'mass', isMetric: false, isSpecial: false, isArbitrary: false, class: 'misc', value: { unit: 'g', value: '2e-1' } },
  { code: '[car_Au]', name: 'carat of gold alloys', property: 'mass fraction', isMetric: false, isSpecial: false, isArbitrary: false, class: 'misc', value: { unit: '/24', value: '1' } },
  { code: '[smoot]', name: 'Smoot', property: 'length', isMetric: false, isSpecial: false, isArbitrary: false, class: 'misc', value: { unit: '[in_i]', value: '67' } },
  { code: '[m/s2/Hz^(1/2)]', name: 'meter per square seconds per square root of hertz', property: 'amplitude spectral density', isMetric: false, isSpecial: true, isArbitrary: false, class: 'misc', value: { unit: 'sqrt(1 m2/s4/Hz)', value: '' } },
  { code: '[NTU]', name: 'Nephelometric Turbidity Unit', property: 'turbidity', isMetric: false, isSpecial: false, isArbitrary: false, class: 'misc', value: { unit: '1', value: '1' } },
  { code: '[FNU]', name: 'Formazin Nephelometric Unit', property: 'turbidity', isMetric: false, isSpecial: false, isArbitrary: false, class: 'misc', value: { unit: '1', value: '1' } },
  { code: 'bit_s', name: 'bit', property: 'amount of information', isMetric: false, isSpecial: true, isArbitrary: false, class: 'infotech', value: { unit: 'ld(1 1)', value: '' } },
  { code: 'bit', name: 'bit', property: 'amount of information', isMetric: true, isSpecial: false, isArbitrary: false, class: 'infotech', value: { unit: '1', value: '1' } },
  { code: 'By', name: 'byte', property: 'amount of information', isMetric: true, isSpecial: false, isArbitrary: false, class: 'infotech', value: { unit: 'bit', value: '8' } },
  { code: 'Bd', name: 'baud', property: 'signal transmission rate', isMetric: true, isSpecial: false, isArbitrary: false, class: 'infotech', value: { unit: '/s', value: '1' } },
] as const;
