import type { ICodeableConcept, IDomainResource, IElement } from '../../base/index.js';
import type { IContactDetail } from '../datatypes/IContactDetail.js';
import type { IIdentifier } from '../datatypes/IIdentifier.js';
import type { IPeriod } from '../datatypes/IPeriod.js';
import type { IUsageContext } from '../datatypes/IUsageContext.js';
import type { ISubscriptionTopicCanFilterBy } from '../backbones/ISubscriptionTopicCanFilterBy.js';
import type { ISubscriptionTopicEventTrigger } from '../backbones/ISubscriptionTopicEventTrigger.js';
import type { ISubscriptionTopicNotificationShape } from '../backbones/ISubscriptionTopicNotificationShape.js';
import type { ISubscriptionTopicResourceTrigger } from '../backbones/ISubscriptionTopicResourceTrigger.js';
import type { PublicationStatusType } from '../../valuesets/index.js';

/**
 * SubscriptionTopic Interface
 * 
 * Describes a stream of resource state changes or events and annotated with labels useful to filter projections from this topic.
 * 
 *
 * @see https://hl7.org/fhir/R4/subscriptiontopic.html
 */
export interface ISubscriptionTopic extends IDomainResource {
  /**
   * The type of resource
   */
  resourceType: 'SubscriptionTopic';

  /**
   * Canonical identifier for this subscription topic definition, represented as a URI (globally unique)
   */
  url: string;
  /**
   * Extension for url
   */
  _url?: IElement;

  /**
   * Business Identifier for this subscription topic
   */
  identifier?: IIdentifier[];

  /**
   * Business version of the subscription topic
   */
  version?: string;
  /**
   * Extension for version
   */
  _version?: IElement;

  /**
   * Name for this subscription topic (Human friendly)
   */
  title?: string;
  /**
   * Extension for title
   */
  _title?: IElement;

  /**
   * Based on FHIR protocol or definition
   */
  derivedFrom?: string[];
  /**
   * Extension for derivedFrom
   */
  _derivedFrom?: IElement;

  /**
   * draft | active | retired | unknown
   */
  status: PublicationStatusType;
  /**
   * Extension for status
   */
  _status?: IElement;

  /**
   * If for testing purposes, not real usage
   */
  experimental?: boolean;
  /**
   * Extension for experimental
   */
  _experimental?: IElement;

  /**
   * Date status first applied
   */
  date?: string;
  /**
   * Extension for date
   */
  _date?: IElement;

  /**
   * The name of the individual or organization that published the SubscriptionTopic
   */
  publisher?: string;
  /**
   * Extension for publisher
   */
  _publisher?: IElement;

  /**
   * Contact details for the publisher
   */
  contact?: IContactDetail[];

  /**
   * Natural language description of the SubscriptionTopic
   */
  description?: string;
  /**
   * Extension for description
   */
  _description?: IElement;

  /**
   * Content intends to support these contexts
   */
  useContext?: IUsageContext[];

  /**
   * Intended jurisdiction of the SubscriptionTopic (if applicable)
   */
  jurisdiction?: ICodeableConcept[];

  /**
   * Why this SubscriptionTopic is defined
   */
  purpose?: string;
  /**
   * Extension for purpose
   */
  _purpose?: IElement;

  /**
   * Use and/or publishing restrictions
   */
  copyright?: string;
  /**
   * Extension for copyright
   */
  _copyright?: IElement;

  /**
   * When SubscriptionTopic is/was approved by publisher
   */
  approvalDate?: string;
  /**
   * Extension for approvalDate
   */
  _approvalDate?: IElement;

  /**
   * Date the Subscription Topic was last reviewed by the publisher
   */
  lastReviewDate?: string;
  /**
   * Extension for lastReviewDate
   */
  _lastReviewDate?: IElement;

  /**
   * The effective date range for the SubscriptionTopic
   */
  effectivePeriod?: IPeriod;

  /**
   * Definition of a resource-based trigger for the subscription topic
   */
  resourceTrigger?: ISubscriptionTopicResourceTrigger[];

  /**
   * Event definitions the SubscriptionTopic
   */
  eventTrigger?: ISubscriptionTopicEventTrigger[];

  /**
   * Properties by which a Subscription can filter notifications from the SubscriptionTopic
   */
  canFilterBy?: ISubscriptionTopicCanFilterBy[];

  /**
   * Properties for describing the shape of notifications generated by this topic
   */
  notificationShape?: ISubscriptionTopicNotificationShape[];

}
