import { BackboneElement } from '../base/BackboneElement.js';
import type {
  IElement,
  ISubscriptionTopicNotificationShape,
} from '@fhir-toolkit/r4b-types';

/** Properties specific to SubscriptionTopicNotificationShape */
const SUBSCRIPTION_TOPIC_NOTIFICATION_SHAPE_PROPERTIES = [
  'resource',
  '_resource',
  'include',
  '_include',
  'revInclude',
  '_revInclude',
] as const;

/**
 * SubscriptionTopicNotificationShape - Properties for describing the shape of notifications generated by this topic
 *
 * @see https://hl7.org/fhir/R4B/subscriptiontopicnotificationshape.html
 *
 * @example
 * const subscriptionTopicNotificationShape = new SubscriptionTopicNotificationShape({
 *   // ... properties
 * });
 */
export class SubscriptionTopicNotificationShape extends BackboneElement implements ISubscriptionTopicNotificationShape {

  // ============================================================================
  // Properties
  // ============================================================================

  /** URL of the Resource that is the focus (main) resource in a notification shape */
  resource: string;

  /** Extension for resource */
  _resource?: IElement;

  /** Include directives, rooted in the resource for this shape */
  include?: string[];

  /** Extension for include */
  _include?: IElement;

  /** Reverse include directives, rooted in the resource for this shape */
  revInclude?: string[];

  /** Extension for revInclude */
  _revInclude?: IElement;

  // ============================================================================
  // Constructor
  // ============================================================================

  constructor(data?: Partial<ISubscriptionTopicNotificationShape>) {
    super(data);
    if (data) {
      this.assignProps(data, SUBSCRIPTION_TOPIC_NOTIFICATION_SHAPE_PROPERTIES);
    }
  }

  // ============================================================================
  // Factory Methods
  // ============================================================================

  /**
   * Create SubscriptionTopicNotificationShape from a JSON object
   */
  static fromJSON(json: ISubscriptionTopicNotificationShape): SubscriptionTopicNotificationShape {
    return new SubscriptionTopicNotificationShape(json);
  }

  // ============================================================================
  // Functional Methods (Immutable Operations)
  // ============================================================================

  /**
   * Create a new SubscriptionTopicNotificationShape with the specified changes (immutable)
   * Does not modify the original instance
   */
  with(changes: Partial<ISubscriptionTopicNotificationShape>): SubscriptionTopicNotificationShape {
    return new SubscriptionTopicNotificationShape({ ...this.toJSON(), ...changes });
  }

  /**
   * Create a new SubscriptionTopicNotificationShape by applying a transformation function (immutable)
   * Does not modify the original instance
   */
  applyTransform(fn: (data: ISubscriptionTopicNotificationShape) => Partial<ISubscriptionTopicNotificationShape>): SubscriptionTopicNotificationShape {
    const currentData = this.toJSON();
    return new SubscriptionTopicNotificationShape({ ...currentData, ...fn(currentData) });
  }

  // ============================================================================
  // Serialization Methods
  // ============================================================================

  /**
   * Convert to plain JSON object (ISubscriptionTopicNotificationShape)
   * Properties are serialized in FHIR-defined order
   */
  toJSON(): ISubscriptionTopicNotificationShape {
    const result: Record<string, any> = {};
    this.serializeBackboneElementTo(result);
    this.serializePropsTo(result, SUBSCRIPTION_TOPIC_NOTIFICATION_SHAPE_PROPERTIES);
    return result as ISubscriptionTopicNotificationShape;
  }

  /**
   * Create a deep clone of this SubscriptionTopicNotificationShape
   */
  clone(): SubscriptionTopicNotificationShape {
    return new SubscriptionTopicNotificationShape(this.deepClone(this.toJSON()));
  }

  // ============================================================================
  // String Representation
  // ============================================================================

  /**
   * Get a string representation of the SubscriptionTopicNotificationShape
   */
  toString(): string {
    const parts: string[] = ['SubscriptionTopicNotificationShape'];
    return parts.join(', ');
  }
}
