/**
 * DataType
 * 
 * A version specific list of the data types defined by the FHIR specification for use as an element  type (any of the FHIR defined data types).
 *
 * @see http://hl7.org/fhir/ValueSet/data-types
 */

export type DataTypeType = 'Address' | 'Age' | 'Annotation' | 'Attachment' | 'BackboneElement' | 'CodeableConcept' | 'CodeableReference' | 'Coding' | 'ContactDetail' | 'ContactPoint' | 'Contributor' | 'Count' | 'DataRequirement' | 'Distance' | 'Dosage' | 'Duration' | 'Element' | 'ElementDefinition' | 'Expression' | 'Extension' | 'HumanName' | 'Identifier' | 'MarketingStatus' | 'Meta' | 'Money' | 'MoneyQuantity' | 'Narrative' | 'ParameterDefinition' | 'Period' | 'Population' | 'ProdCharacteristic' | 'ProductShelfLife' | 'Quantity' | 'Range' | 'Ratio' | 'RatioRange' | 'Reference' | 'RelatedArtifact' | 'SampledData' | 'Signature' | 'SimpleQuantity' | 'Timing' | 'TriggerDefinition' | 'UsageContext' | 'base64Binary' | 'boolean' | 'canonical' | 'code' | 'date' | 'dateTime' | 'decimal' | 'id' | 'instant' | 'integer' | 'markdown' | 'oid' | 'positiveInt' | 'string' | 'time' | 'unsignedInt' | 'uri' | 'url' | 'uuid' | 'xhtml';

export enum DataTypeEnum {
  /** Address */
  Address = 'Address',
  /** Age */
  Age = 'Age',
  /** Annotation */
  Annotation = 'Annotation',
  /** Attachment */
  Attachment = 'Attachment',
  /** BackboneElement */
  Backboneelement = 'BackboneElement',
  /** CodeableConcept */
  Codeableconcept = 'CodeableConcept',
  /** CodeableReference */
  Codeablereference = 'CodeableReference',
  /** Coding */
  Coding = 'Coding',
  /** ContactDetail */
  Contactdetail = 'ContactDetail',
  /** ContactPoint */
  Contactpoint = 'ContactPoint',
  /** Contributor */
  Contributor = 'Contributor',
  /** Count */
  Count = 'Count',
  /** DataRequirement */
  Datarequirement = 'DataRequirement',
  /** Distance */
  Distance = 'Distance',
  /** Dosage */
  Dosage = 'Dosage',
  /** Duration */
  Duration = 'Duration',
  /** Element */
  Element = 'Element',
  /** ElementDefinition */
  Elementdefinition = 'ElementDefinition',
  /** Expression */
  Expression = 'Expression',
  /** Extension */
  Extension = 'Extension',
  /** HumanName */
  Humanname = 'HumanName',
  /** Identifier */
  Identifier = 'Identifier',
  /** MarketingStatus */
  Marketingstatus = 'MarketingStatus',
  /** Meta */
  Meta = 'Meta',
  /** Money */
  Money = 'Money',
  /** MoneyQuantity */
  Moneyquantity = 'MoneyQuantity',
  /** Narrative */
  Narrative = 'Narrative',
  /** ParameterDefinition */
  Parameterdefinition = 'ParameterDefinition',
  /** Period */
  Period = 'Period',
  /** Population */
  Population = 'Population',
  /** ProdCharacteristic */
  Prodcharacteristic = 'ProdCharacteristic',
  /** ProductShelfLife */
  Productshelflife = 'ProductShelfLife',
  /** Quantity */
  Quantity = 'Quantity',
  /** Range */
  Range = 'Range',
  /** Ratio */
  Ratio = 'Ratio',
  /** RatioRange */
  Ratiorange = 'RatioRange',
  /** Reference */
  Reference = 'Reference',
  /** RelatedArtifact */
  Relatedartifact = 'RelatedArtifact',
  /** SampledData */
  Sampleddata = 'SampledData',
  /** Signature */
  Signature = 'Signature',
  /** SimpleQuantity */
  Simplequantity = 'SimpleQuantity',
  /** Timing */
  Timing = 'Timing',
  /** TriggerDefinition */
  Triggerdefinition = 'TriggerDefinition',
  /** UsageContext */
  Usagecontext = 'UsageContext',
  /** base64Binary */
  Base64binary = 'base64Binary',
  /** boolean */
  Boolean = 'boolean',
  /** canonical */
  Canonical = 'canonical',
  /** code */
  Code = 'code',
  /** date */
  Date = 'date',
  /** dateTime */
  Datetime = 'dateTime',
  /** decimal */
  Decimal = 'decimal',
  /** id */
  Id = 'id',
  /** instant */
  Instant = 'instant',
  /** integer */
  Integer = 'integer',
  /** markdown */
  Markdown = 'markdown',
  /** oid */
  Oid = 'oid',
  /** positiveInt */
  Positiveint = 'positiveInt',
  /** string */
  String = 'string',
  /** time */
  Time = 'time',
  /** unsignedInt */
  Unsignedint = 'unsignedInt',
  /** uri */
  Uri = 'uri',
  /** url */
  Url = 'url',
  /** uuid */
  Uuid = 'uuid',
  /** XHTML */
  Xhtml = 'xhtml',
}

export const DataTypeValues = ['Address', 'Age', 'Annotation', 'Attachment', 'BackboneElement', 'CodeableConcept', 'CodeableReference', 'Coding', 'ContactDetail', 'ContactPoint', 'Contributor', 'Count', 'DataRequirement', 'Distance', 'Dosage', 'Duration', 'Element', 'ElementDefinition', 'Expression', 'Extension', 'HumanName', 'Identifier', 'MarketingStatus', 'Meta', 'Money', 'MoneyQuantity', 'Narrative', 'ParameterDefinition', 'Period', 'Population', 'ProdCharacteristic', 'ProductShelfLife', 'Quantity', 'Range', 'Ratio', 'RatioRange', 'Reference', 'RelatedArtifact', 'SampledData', 'Signature', 'SimpleQuantity', 'Timing', 'TriggerDefinition', 'UsageContext', 'base64Binary', 'boolean', 'canonical', 'code', 'date', 'dateTime', 'decimal', 'id', 'instant', 'integer', 'markdown', 'oid', 'positiveInt', 'string', 'time', 'unsignedInt', 'uri', 'url', 'uuid', 'xhtml'] as const;
