import type { IBackboneElement, IElement } from '../../base/index.js';

/**
 * SubscriptionTopicNotificationShape Interface
 * 
 * Properties for describing the shape of notifications generated by this topic
 * 
 *
 * @see https://hl7.org/fhir/R4/subscriptiontopicnotificationshape.html
 */
export interface ISubscriptionTopicNotificationShape extends IBackboneElement {
  /**
   * URL of the Resource that is the focus (main) resource in a notification shape
   */
  resource: string;
  /**
   * Extension for resource
   */
  _resource?: IElement;

  /**
   * Include directives, rooted in the resource for this shape
   */
  include?: string[];
  /**
   * Extension for include
   */
  _include?: IElement;

  /**
   * Reverse include directives, rooted in the resource for this shape
   */
  revInclude?: string[];
  /**
   * Extension for revInclude
   */
  _revInclude?: IElement;

}
