import { DomainResource } from '../base/DomainResource.js';
import type {
  ICodeableConcept,
  IContactDetail,
  IElement,
  IIdentifier,
  IPeriod,
  ISubscriptionTopic,
  ISubscriptionTopicCanFilterBy,
  ISubscriptionTopicEventTrigger,
  ISubscriptionTopicNotificationShape,
  ISubscriptionTopicResourceTrigger,
  IUsageContext,
  PublicationStatusType,
} from '@fhir-toolkit/r4b-types';

/** Properties specific to SubscriptionTopic */
const SUBSCRIPTION_TOPIC_PROPERTIES = [
  'url',
  '_url',
  'identifier',
  'version',
  '_version',
  'title',
  '_title',
  'derivedFrom',
  '_derivedFrom',
  'status',
  '_status',
  'experimental',
  '_experimental',
  'date',
  '_date',
  'publisher',
  '_publisher',
  'contact',
  'description',
  '_description',
  'useContext',
  'jurisdiction',
  'purpose',
  '_purpose',
  'copyright',
  '_copyright',
  'approvalDate',
  '_approvalDate',
  'lastReviewDate',
  '_lastReviewDate',
  'effectivePeriod',
  'resourceTrigger',
  'eventTrigger',
  'canFilterBy',
  'notificationShape',
] as const;

/**
 * SubscriptionTopic - Describes a stream of resource state changes or events and annotated with labels useful to filter projections from this topic.
 *
 * @see https://hl7.org/fhir/R4/subscriptiontopic.html
 *
 * @example
 * const subscriptionTopic = new SubscriptionTopic({
 *   resourceType: 'SubscriptionTopic',
 *   // ... properties
 * });
 */
export class SubscriptionTopic extends DomainResource implements ISubscriptionTopic {
  readonly resourceType = 'SubscriptionTopic' as const;

  // ============================================================================
  // Properties
  // ============================================================================

  /** Canonical identifier for this subscription topic definition, represented as a URI (globally unique) */
  url: string;

  /** Extension for url */
  _url?: IElement;

  /** Business Identifier for this subscription topic */
  identifier?: IIdentifier[];

  /** Business version of the subscription topic */
  version?: string;

  /** Extension for version */
  _version?: IElement;

  /** Name for this subscription topic (Human friendly) */
  title?: string;

  /** Extension for title */
  _title?: IElement;

  /** Based on FHIR protocol or definition */
  derivedFrom?: string[];

  /** Extension for derivedFrom */
  _derivedFrom?: IElement;

  /** draft | active | retired | unknown */
  status: PublicationStatusType;

  /** Extension for status */
  _status?: IElement;

  /** If for testing purposes, not real usage */
  experimental?: boolean;

  /** Extension for experimental */
  _experimental?: IElement;

  /** Date status first applied */
  date?: string;

  /** Extension for date */
  _date?: IElement;

  /** The name of the individual or organization that published the SubscriptionTopic */
  publisher?: string;

  /** Extension for publisher */
  _publisher?: IElement;

  /** Contact details for the publisher */
  contact?: IContactDetail[];

  /** Natural language description of the SubscriptionTopic */
  description?: string;

  /** Extension for description */
  _description?: IElement;

  /** Content intends to support these contexts */
  useContext?: IUsageContext[];

  /** Intended jurisdiction of the SubscriptionTopic (if applicable) */
  jurisdiction?: ICodeableConcept[];

  /** Why this SubscriptionTopic is defined */
  purpose?: string;

  /** Extension for purpose */
  _purpose?: IElement;

  /** Use and/or publishing restrictions */
  copyright?: string;

  /** Extension for copyright */
  _copyright?: IElement;

  /** When SubscriptionTopic is/was approved by publisher */
  approvalDate?: string;

  /** Extension for approvalDate */
  _approvalDate?: IElement;

  /** Date the Subscription Topic was last reviewed by the publisher */
  lastReviewDate?: string;

  /** Extension for lastReviewDate */
  _lastReviewDate?: IElement;

  /** The effective date range for the SubscriptionTopic */
  effectivePeriod?: IPeriod;

  /** Definition of a resource-based trigger for the subscription topic */
  resourceTrigger?: ISubscriptionTopicResourceTrigger[];

  /** Event definitions the SubscriptionTopic */
  eventTrigger?: ISubscriptionTopicEventTrigger[];

  /** Properties by which a Subscription can filter notifications from the SubscriptionTopic */
  canFilterBy?: ISubscriptionTopicCanFilterBy[];

  /** Properties for describing the shape of notifications generated by this topic */
  notificationShape?: ISubscriptionTopicNotificationShape[];

  // ============================================================================
  // Constructor
  // ============================================================================

  constructor(data?: Partial<ISubscriptionTopic>) {
    super(data);
    if (data) {
      this.assignProps(data, SUBSCRIPTION_TOPIC_PROPERTIES);
    }
  }

  // ============================================================================
  // Factory Methods
  // ============================================================================

  /**
   * Create SubscriptionTopic from a JSON object
   */
  static fromJSON(json: ISubscriptionTopic): SubscriptionTopic {
    return new SubscriptionTopic(json);
  }

  // ============================================================================
  // Functional Methods (Immutable Operations)
  // ============================================================================

  /**
   * Create a new SubscriptionTopic with the specified changes (immutable)
   * Does not modify the original instance
   */
  with(changes: Partial<ISubscriptionTopic>): SubscriptionTopic {
    return new SubscriptionTopic({ ...this.toJSON(), ...changes });
  }

  /**
   * Create a new SubscriptionTopic by applying a transformation function (immutable)
   * Does not modify the original instance
   */
  applyTransform(fn: (data: ISubscriptionTopic) => Partial<ISubscriptionTopic>): SubscriptionTopic {
    const currentData = this.toJSON();
    return new SubscriptionTopic({ ...currentData, ...fn(currentData) });
  }

  // ============================================================================
  // Serialization Methods
  // ============================================================================

  /**
   * Convert to plain JSON object (ISubscriptionTopic)
   * Properties are serialized in FHIR-defined order
   */
  toJSON(): ISubscriptionTopic {
    const result: Record<string, any> = { resourceType: this.resourceType };
    this.serializeDomainResourceTo(result);
    this.serializePropsTo(result, SUBSCRIPTION_TOPIC_PROPERTIES);
    return result as ISubscriptionTopic;
  }

  /**
   * Create a deep clone of this SubscriptionTopic
   */
  clone(): SubscriptionTopic {
    return new SubscriptionTopic(this.deepClone(this.toJSON()));
  }

  // ============================================================================
  // String Representation
  // ============================================================================

  /**
   * Get a string representation of the SubscriptionTopic
   */
  toString(): string {
    const parts: string[] = ['SubscriptionTopic'];
    if (this.id) parts.push(`id=${this.id}`);
    return parts.join(', ');
  }
}
